# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Circumflex < Formula
  desc "circumflex is a command line tool for browsing Hacker News in your terminal"
  homepage "https://github.com/bensadeh/circumflex/"
  version "3.2"
  license "AGPL-3.0-only"

  depends_on "less"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bensadeh/circumflex/releases/download/3.2/circumflex_3.2_darwin_amd64.tar.gz"
      sha256 "3f8561386a8e904e8ead31c78d81bbaa12d2585e103cee489a9716d3a3234ff6"

      def install
        bin.install "circumflex" => "clx"
        man1.install "#{buildpath}/share/man/clx.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bensadeh/circumflex/releases/download/3.2/circumflex_3.2_darwin_arm64.tar.gz"
      sha256 "cae9b893edb361534935bbb333cd6afffeb26fb4bedbcd56e7618ac243e212d3"

      def install
        bin.install "circumflex" => "clx"
        man1.install "#{buildpath}/share/man/clx.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bensadeh/circumflex/releases/download/3.2/circumflex_3.2_linux_arm64.tar.gz"
      sha256 "b36933fd5be4b29f6894409ee8c1501a6809a18c4b9c48f106160e97dd04fdf4"

      def install
        bin.install "circumflex" => "clx"
        man1.install "#{buildpath}/share/man/clx.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bensadeh/circumflex/releases/download/3.2/circumflex_3.2_linux_amd64.tar.gz"
      sha256 "46c8655c68314b6cbe2909c560bb94bf62ccf364f0314307e5528bc9b24d5e16"

      def install
        bin.install "circumflex" => "clx"
        man1.install "#{buildpath}/share/man/clx.1"
      end
    end
  end
end
