# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Circumflex < Formula
  desc "circumflex is Hacker News in your terminal"
  homepage "https://github.com/bensadeh/circumflex/"
  version "0.6"
  license "AGPL-3.0-only"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bensadeh/circumflex/releases/download/0.6/circumflex_0.6_macOS_64-bit.tar.gz"
    sha256 "8bb6304ffaa80fc022ad2c4226e632daec78874768886634e203860597cf5e3a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bensadeh/circumflex/releases/download/0.6/circumflex_0.6_Linux_64-bit.tar.gz"
    sha256 "1338c847846dfb255c61d2b226cadc1b54490dac8f3567e023e92eb7b4d72cf5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/bensadeh/circumflex/releases/download/0.6/circumflex_0.6_Linux_arm64.tar.gz"
    sha256 "3164536a0282ea06be4b734ca393688ff3fdb8208cf938ba73b7f59a0cde61ec"
  end

  depends_on "less"

  def install
    bin.install "circumflex" => "clx"
  end
end
